3. Write a function `my_is_similar(s1,s2,tol)` where `s1` and `s2` are strings, not necessarily of the same size, and `tol` is a scalar value stricty larger than zero. From `s1` and `s2`, the function should construct two vectors, `v1` and `v2`, where `v1[0]` is the number of a's in `s1`, `v1[1]` is the number of b's in `s1`, and so on until `v1[25]`, which is the number of 's in `v1`. The vector `v2` should be similarly constructed from `s2`. The output should be $1$ if the absolute value of the angle between `v1` and `v2` is less than `tol`, that is, $\left|\theta\right| <$ `tol`.

In [1]:
import numpy as np

def my_is_similar(s1, s2, tol):
    v1 = np.array([s1.count(chr(i)) for i in range(97, 123)])
    v2 = np.array([s2.count(chr(i)) for i in range(97, 123)])

    norm_v1 = np.linalg.norm(v1)
    norm_v2 = np.linalg.norm(v2)

    if norm_v1 == 0 or norm_v2 == 0:
        return 0

    cos_theta = np.dot(v1, v2)/(norm_v1*norm_v2)
    cos_theta = np.clip(cos_theta, -1, 1)

    theta = np.arccos(cos_theta)
    if abs(theta) < tol:
        return 1
    else:
        return 0

print(my_is_similar("same", "same", 0.1))
print(my_is_similar("a","b",0.1))

1
0


4. Write a function `my_make_lin_ind(A)` where $A$ and $B$ are matrices. Let $\text{rank}(A) = n$. Then $B$ should be a matrix containing the first $n$ columns of $A$ that are all linearly independent. Note that this implies that $B$ has full rank.

In [2]:
import numpy as np

def my_make_lin_ind(A):
    n_rows, n_cols = A.shape
    rank = np.linalg.matrix_rank(A)

    B_cols = []

    for j in range(0, n_cols):
        if len(B_cols) == rank:
            break
            
        if len(B_cols) > 0:
            candidate_matrix = A[:, B_cols + [j]]
        else:
            candidate_matrix = A[:, [j]]

        if np.linalg.matrix_rank(candidate_matrix) > len(B_cols):
            B_cols.append(j)
    
    B = A[:, B_cols]
    return B

A = np.array([[12,24,0,11,-24,18,15],
              [19,38,0,10,-31,25,9],
              [1,2,0,21,-5,3,20],
              [6,12,0,13,-10,8,5],
              [22,44,0,2,-12,17,23]])

print(my_make_lin_ind(A))

[[ 12  11 -24  15]
 [ 19  10 -31   9]
 [  1  21  -5  20]
 [  6  13 -10   5]
 [ 22   2 -12  23]]


12. Write a function `my_flow_calcultor(S,d)` where `S` is a $1 \times 2$ vector representing the capacity of each power supply station, and `d` is a $1 \times 5$ row vector representing the demands at each node. The output argument, `f`, should be a $1 \times 7$ row vector denoting the flows in the network. The flows contained in `f` should satisfy all the constraints of the system, like power generation and demands. Note that there may be more than one solution to the system of equations. The total flow into a node must equal the total flow out of the node plus the demand; that is, for each node $i$, $f_{\text{inflow}} = f_{\text{outflow}} + d_{i}$. You may assume that $\sum S_{j} = \sum d_{i}$.

In [13]:
import numpy as np

def my_flow_calculator(S,d):
    """
    The equations are:
    f1                               = S1
                   f4 + f5           = S2
            - f3 + f4      - f6      = d1
                        f5      - f7 = d2
         f2                          = d3
    f1 - f2 + f3                     = d4
                             f6 + f7 = d5

    Represent this system of equations as Af = d.
    """

    d = np.concatenate((S, d), axis = 1).T

    A = np.array([
        [1, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 1, 1, 0, 0],
        [0, 0, -1, 1, 0, -1, 0],
        [0, 0, 0, 0, 1, 0, -1],
        [0, 1, 0, 0, 0, 0, 0],
        [1, -1, 1, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 1, 1]
    ])

    # Matrix is singular, least squares solution is found instead.
    f, _, _, _ = np.linalg.lstsq(A, d, rcond = None)

    return(f.T)


S = np.array([[10, 10]])
d = np.array([[4, 4, 4, 4, 4]])
print(my_flow_calculator(S, d))

S = np.array([[10, 10]])
d = np.array([[3, 4, 5, 4, 4]])
print(my_flow_calculator(S, d))  

[[10.   4.  -2.   4.5  5.5  2.5  1.5]]
[[10.   5.  -1.   4.5  5.5  2.5  1.5]]
