3. Write a function `my_is_similar(s1,s2,tol)` where `s1` and `s2` are strings, not necessarily of the same size, and `tol` is a scalar value stricty larger than zero. From `s1` and `s2`, the function should construct two vectors, `v1` and `v2`, where `v1[0]` is the number of a's in `s1`, `v1[1]` is the number of b's in `s1`, and so on until `v1[25]`, which is the number of 's in `v1`. The vector `v2` should be similarly constructed from `s2`. The output should be $1$ if the absolute value of the angle between `v1` and `v2` is less than `tol`, that is, $\left|\theta\right| <$ `tol`.

In [4]:
import numpy as np

def my_is_similar(s1, s2, tol):
    v1 = np.array([s1.count(chr(i)) for i in range(97, 123)])
    v2 = np.array([s2.count(chr(i)) for i in range(97, 123)])

    norm_v1 = np.linalg.norm(v1)
    norm_v2 = np.linalg.norm(v2)

    if norm_v1 == 0 or norm_v2 == 0:
        return 0

    cos_theta = np.dot(v1, v2)/(norm_v1*norm_v2)
    cos_theta = np.clip(cos_theta, -1, 1)

    theta = np.arccos(cos_theta)
    if abs(theta) < tol:
        return 1
    else:
        return 0

print(my_is_similar("same", "same", 0.1))
print(my_is_similar("a","b",0.1))

1
0


4. Write a function `my_make_lin_ind(A)` where $A$ and $B$ are matrices. Let $\text{rank}(A) = n$. Then $B$ should be a matrix containing the first $n$ columns of $A$ that are all linearly independent. Note that this implies that $B$ has full rank.

In [7]:
import numpy as np

def my_make_lin_ind(A):
    n_rows, n_cols = A.shape
    rank = np.linalg.matrix_rank(A)

    B_cols = []

    for j in range(0, n_cols):
        if len(B_cols) == rank:
            break
            
        if len(B_cols) > 0:
            candidate_matrix = A[:, B_cols + [j]]
        else:
            candidate_matrix = A[:, [j]]

        if np.linalg.matrix_rank(candidate_matrix) > len(B_cols):
            B_cols.append(j)
    
    B = A[:, B_cols]
    return B

A = np.array([[12,24,0,11,-24,18,15],
              [19,38,0,10,-31,25,9],
              [1,2,0,21,-5,3,20],
              [6,12,0,13,-10,8,5],
              [22,44,0,2,-12,17,23]])

print(my_make_lin_ind(A))

[[ 12  11 -24  15]
 [ 19  10 -31   9]
 [  1  21  -5  20]
 [  6  13 -10   5]
 [ 22   2 -12  23]]
