1. Assign the value $2$ to the variable `x` and the value $3$ to the variable `y`. Clear just the variable `x`.

In [1]:
x, y = 2, 3
del x

2. Write a line of code that generates the following error: `NameError: name "x" is not defined`.

In [4]:
x

NameError: name 'x' is not defined

3. Let `x = 10` and `y = 3`. Write a line code with the following assignments.

In [9]:
import math
x, y = 10, 3
u = x + y
v = x*y
w = x/y
z = math.sin(x)
r = 8*math.sin(x)
s = 5*math.sin(x*y)
p = x**y

4. Show all the variables in the notebook.

In [10]:
%whos

Variable   Type      Data/Info
------------------------------
math       module    <module 'math' (built-in)>
p          int       1000
r          float     -4.352168887114958
s          float     -4.940158120464309
u          int       13
v          int       30
w          float     3.3333333333333335
x          int       10
y          int       3
z          float     -0.5440211108893698


5. Assign string "123" to the variable `S`. Convert the string into a float type and assign the output to the variable `N`. Verify that `S` is a string and `N` is a float using the `type` function.

In [11]:
S = "123"
N = float(S)
print(type(S))
print(type(N))

<class 'str'>
<class 'float'>


6. Assign the string "HELLO" to the variable `s1` and the string "hello" to the variable `s2`. Use the `==` operator to show that they are not equal. Use the `==` operator to show that `s1` and `s2` are equal if lower method is used on `s1`, or the if the upper method is used on `s2`.

In [12]:
s1 = "HELLO"
s2 = "hello"
print(s1 == s2)
print(s1.lower() == s2)
print(s1 == s2.upper())

False
True
True


7. Use the print function to generate the following strings.

In [15]:
print("The word \"Engineering\" has 11 letters.")
print("The word \"Book\" has 4 letters.")

The word "Engineering" has 11 letters.
The word "Book" has 4 letters.


8. Check if "Python" is in "Python is great!"

In [22]:
"Python" in "Python is great!"

True

9. Get the word "great" from "Python is great!"

In [23]:
"Python is great!".split()[-1][:-1]

'great'

10. Assign the list `[1, 8, 9, 15]` to a variable `list_a` and insert $2$ at index $1$ using the insert method. Append $4$ to `list_a` using the `append` method.

In [26]:
list_a = [1,8,9,15]
print(list_a)
list_a.insert(1,2)
print(list_a)
list_a.append(4)
print(list_a)

[1, 8, 9, 15]
[1, 2, 8, 9, 15]
[1, 2, 8, 9, 15, 4]


11. Sort `list_a` in ascending order.

In [27]:
list_a.sort()
print(list_a)

[1, 2, 4, 8, 9, 15]


12. Turn "Python is great!" into a list.

In [29]:
list("Python is great!")

['P',
 'y',
 't',
 'h',
 'o',
 'n',
 ' ',
 'i',
 's',
 ' ',
 'g',
 'r',
 'e',
 'a',
 't',
 '!']

13. Create one tuple with elements "One",$1$ and assign it to `tuple_a`.

In [30]:
tuple_a = ("One", 1)
print(tuple_a)

('One', 1)


14. Get the second elements of `tuple_a`.

In [31]:
tuple_a[1]

1

15. Get the unique elements from $(2,3,2,3,1,2,5)$.

In [33]:
unique = set((2,3,2,3,1,2,5))
unique

{1, 2, 3, 5}

16. Assign $(2,3,2)$ to `set_a` and $(1,2,3)$ to `set_b`. Obtain the following.

In [35]:
set_a = set((2,3,2))
set_b = set((1,2,3))

print(set_a | set_b)
print(set_a & set_b)
print(set_a.difference(set_b))

{1, 2, 3}
{2, 3}
set()


17. Create a dictionary that has the keys "A", "B", "C" with the values "a", "b", "c", respectively. Print all the keys in the dictionary.

In [36]:
mydict = {"A":"a","B":"b","C":"c"}
mydict.keys()

dict_keys(['A', 'B', 'C'])

18. Check if key "B" is in the dictionary defined above.

In [37]:
"B" in mydict

True

19. Create array `x` and `y`, where `x = [1,4,3,2,9,4]` and `y=[2,3,4,1,2,3]`. Compute the assignments from Problem 3.

In [43]:
import numpy as np
x, y = [1,4,3,2,9,4], [2,3,4,1,2,3]
u = x + y
# v = x*y Not valid
# w = x/y Not valid
z = np.sin(x)
r = 8*np.sin(x)
# s = 5*np.sin(x*y) Not valid
# p = x**y Not valid

20. Generate an array with size $100$ evenly spaced between $-10$ to $10$ using `linspace` function in `NumPy`.

In [44]:
np.linspace(-10,10,100)

array([-10.        ,  -9.7979798 ,  -9.5959596 ,  -9.39393939,
        -9.19191919,  -8.98989899,  -8.78787879,  -8.58585859,
        -8.38383838,  -8.18181818,  -7.97979798,  -7.77777778,
        -7.57575758,  -7.37373737,  -7.17171717,  -6.96969697,
        -6.76767677,  -6.56565657,  -6.36363636,  -6.16161616,
        -5.95959596,  -5.75757576,  -5.55555556,  -5.35353535,
        -5.15151515,  -4.94949495,  -4.74747475,  -4.54545455,
        -4.34343434,  -4.14141414,  -3.93939394,  -3.73737374,
        -3.53535354,  -3.33333333,  -3.13131313,  -2.92929293,
        -2.72727273,  -2.52525253,  -2.32323232,  -2.12121212,
        -1.91919192,  -1.71717172,  -1.51515152,  -1.31313131,
        -1.11111111,  -0.90909091,  -0.70707071,  -0.50505051,
        -0.3030303 ,  -0.1010101 ,   0.1010101 ,   0.3030303 ,
         0.50505051,   0.70707071,   0.90909091,   1.11111111,
         1.31313131,   1.51515152,   1.71717172,   1.91919192,
         2.12121212,   2.32323232,   2.52525253,   2.72

21. Let `array_a` be an arary `[-1,0,1,2,0,3]`. Write a command that will return an array consisting of all the elements of `array_a` that are larger than zero.

In [46]:
array_a = np.array([-1,0,1,2,0,3])
array_a[array_a > 0]

array([1, 2, 3])

22. Create an array $y = \begin{pmatrix} 3 & 5 & 3 \\ 2 & 2 & 5 \\ 3 & 8 & 9 \end{pmatrix}$ and calculate its transpose.

In [47]:
y = np.array([[3,5,3],[2,2,5],[3,8,9]])
print(y)
print(y.T)

[[3 5 3]
 [2 2 5]
 [3 8 9]]
[[3 2 3]
 [5 2 8]
 [3 5 9]]


23. Create a $2 \times 4$ zero array.

In [52]:
array = np.zeros((2,4))
array

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

24. Change the second column in the above array to $1$.

In [54]:
array[:, 1] = 1
array

array([[0., 1., 0., 0.],
       [0., 1., 0., 0.]])