1. Write a function `my_sinh(x)` where the output `y` is the hyperbolic sine computed on `x`.

In [1]:
import math
def my_sinh(x):
    return (math.exp(x)-math.exp(-x))/2
    
print(my_sinh(0))
print(my_sinh(1))
print(my_sinh(2))

0.0
1.1752011936438014
3.626860407847019


2. Write a function `my_checker_board(n)` where the output `m` is an $n \times n$ array with alternating $1$'s and $0$'s. The upper-left element is always 1, and assume that $n$ is a strictly positive integer.

In [3]:
import numpy as np

def my_checker_board(n: int):
    m = np.zeros((n,n))
    m[::2,::2] = 1
    m[1::2,1::2] = 1
    return m

print(my_checker_board(5))

[[1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0.]
 [1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0.]
 [1. 0. 1. 0. 1.]]


3. Write a function `my_triangle(b,h)`, where the output is the area of a triangle with base `b` and height `h`.

In [5]:
def my_triangle(b: float, h: float):
    return 0.5*b*h

my_triangle(12, 5)

30.0

4. Write a function `my_split_matrix(m)`, where `m` is an array, and the output is a list `[m1,m2]` where `m1` is the left half of `m`, and `m2` is the right half of `m`. In the case where there is an odd number of columns, the middle column should go to `m1`. Assume that `m` has at least two columns.

In [7]:
def my_split_matrix(m):
    middle = (m.shape[1]//2) + (m.shape[1]%2)
    m1 = m[:,:middle]
    m2 = m[:,middle:]
    return [m1,m2]

m = np.array([[1,2,3],[4,5,6],[7,8,9]])
m1, m2 = my_split_matrix(m)
print(m)
print(m1)
print(m2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2]
 [4 5]
 [7 8]]
[[3]
 [6]
 [9]]


5. Write a function `my_cylinder(r,h)`, where `r` and `h` are the radius and height of a cylinder, respectively, and the output is a list `[s,v]` where `s` and `v` are the surface are and the volume of the same cylinder, respectively.

In [13]:
from math import pi
print(pi)
def my_cylinder(r, h):
    v = pi*r*r*h
    s = 2*pi*r*r + 2*pi*r*h
    return [s,v]

my_cylinder(1,5)

3.141592653589793


[37.69911184307752, 15.707963267948966]

6. Write a function `my_n_odds(a)`, where `a` is a one-dimensional array of floats the output is the number of odd numbers in `a`.

In [14]:
def my_n_odds(a):
    return np.sum(np.floor(a) % 2 != 0)

my_n_odds(np.arange(2,100,2))

0

7. Write a function `my_twos(m,n)` where the output is an $m \times n$ array of twos. Assume that `m` and `n` are strictly positive integers.

In [15]:
def my_twos(m,n):
    return np.full((m,n),2)

my_twos(3,2)

array([[2, 2],
       [2, 2],
       [2, 2]])

8. Write a lambda function that takes in inputs `x` and `y`, and the output is the value of `x-y`.

In [16]:
difference = lambda x, y: x-y
difference(15,254)

-239

9. Write a function `add_string(s1,s2)` where the output is the concatenation of the strings `s1` and `s2`.

In [18]:
def add_string(s1: str, s2: str) -> str:
    return s1 + s2

add_string("Python","is great!")

'Pythonis great!'

10. Generate the following errors.

In [19]:
def fun(a):
    return a

fun()

TypeError: fun() missing 1 required positional argument: 'a'

In [20]:
def fun(a):
return a

IndentationError: expected an indented block after function definition on line 1 (757296960.py, line 2)

11. Write a function `greeting(name, age)` where `name` is a string, `age` is a float, and the output is a string "Hi, my name is XXX and I am XXX years old".

In [21]:
def greeting(name: str, age: float) -> str:
    return "Hi, my name is " + name + " and I am " + str(age) + " years old."

greeting("Ramdas",18)

'Hi, my name is Ramdas and I am 18 years old.'

12. Let `r1` and `r2` be the radius of circles with the same center and let `r2 > r1`. Write a function `my_donut_area(r1,r2)` where the output is the area outside of the circle with radius `r1` and inside of the circle with radius `r2`. Make sure the function is vectorized. Assume that `r1` and `r2` are one-dimensional arrays of the same size.

In [22]:
def my_donut_area(r1,r2):
    return pi*(r2**2 - r1**2)

my_donut_area(np.arange(1,4), np.arange(2,7,2))

array([ 9.42477796, 37.69911184, 84.82300165])

13. Write a function `my_within_tolerance(A,a,tol)` where the output is an array or list of the indices in `A` such that $|A-a|<\text{tol}$. Assume that `A` is a one-dimensional float list or array, and that `a` and `tol` are one by one floats.

In [23]:
def my_within_tolerance(A,a,tol):
    A = np.array(A)
    return np.where(np.abs(A-a)<tol)[0]

my_within_tolerance([0,1,2,3],1.5,0.75)

array([1, 2], dtype=int64)

14. Write a function `bounding_array(A,top,bottom)` where the output is equal to the array `A` wherever `bottom < A < top`, the output is equal to `bottom` wherever `A <= bottom`, and the output is equal to `top` wherever `A >= top`. Assuyme that `A` is a one-dimensional float array and that `top` and `bottom` are one by one floats.

In [25]:
def bounding_array(A,top,bottom):
    A = np.array(A)
    A[A > top] = top
    A[A < bottom] = bottom
    return A

bounding_array(np.arange(-5,6,1),3,-3)

array([-3, -3, -3, -2, -1,  0,  1,  2,  3,  3,  3])