6. Write a function `my_chebyshev_poly(n,x)` where the output `y` is the `n`th Chebyshev polynomial of the first kind evaluated at `x`. Assume that `x` is a list.

In [2]:
def my_chebyshev_poly1(n,x):
    def T(n,x):
        if n == 0:
            return 1
        if n == 1:
            return x
        return 2*x*T(n-1,x) - T(n-2,x)

    y = []
    for i in x:
        y.append(T(n,i))
    
    return y

x = [1,2,3,4,5]
print(my_chebyshev_poly1(0,x))
print(my_chebyshev_poly1(1,x))
print(my_chebyshev_poly1(3,x))

[1, 1, 1, 1, 1]
[1, 2, 3, 4, 5]
[1, 26, 99, 244, 485]


3. Write a function `my_ackerman(m,n)` where the output is the Ackermann function computed for `m` and `n`.

In [1]:
import sys

sys.setrecursionlimit(100000)

def my_ackermann(m,n):
    if m == 0:
        return n+1
    if n == 0:
        return my_ackermann(m-1, 1)
    return my_ackermann(m-1, my_ackermann(m, n-1))

print(my_ackermann(2,3))
print(my_ackermann(3,3))
print(my_ackermann(3,4))

9
61
125


6. Write a recursive function with the header `my_golden_ratio(n)`, where the output is the $n$th approximation of the golden ratio according to the continued fraction recursive relationship.

In [5]:
def my_golden_ratio(n):
    if n == 1:
        return 1
    return 1 + 1/(my_golden_ratio(n-1))

print(my_golden_ratio(15))

1.6180327868852458


8. Write a function with `my_pascal_row(m)` where the output variable `row` is the `m`th row of the Pascal triangle and must be a list. Assume that `m` is a strictly positive integer.

In [12]:
def my_pascal_row(m):
    if m == 1:
        return [1]
    
    row = []
    prev_row = [0] + my_pascal_row(m-1) + [0]

    for i in range(len(prev_row)-1):
        row.append(prev_row[i]+prev_row[i+1])

    return row

print(my_pascal_row(5))

[1, 4, 6, 4, 1]


9. Consider an $n \times n$ matrix of the following form:
$$\begin{pmatrix}
1 & 1 & 1 & 1 & 1 \\
1 & 0 & 0 & 0 & 0 \\
1 & 0 & 1 & 1 & 0 \\
1 & 0 & 0 & 1 & 0 \\
1 & 1 & 1 & 1 & 0
\end{pmatrix} $$
Write a function `my_spiral_ones(n)` that produces a $n \times n$ matrix of the given form.

In [16]:
import numpy as np

def my_spiral_ones(n):
    if n == 1:
        return [[1]]
    
    spiral = my_spiral_ones(n-1)

    if n%4 == 2:
        for i in range(len(spiral)):
            spiral[i].append(1)
        spiral = spiral + [[0 for _ in range(n-1)] + [1]]

    elif n%4 == 3:
        for i in range(len(spiral)):
            spiral[i].insert(0, 0)
        spiral = [[0 for _ in range(n)]] + spiral

    elif n%4 == 0:
        for i in range(len(spiral)):
            spiral[i].insert(0, 1)
        spiral = spiral + [[1 for _ in range(n)]]

    elif n%4 == 1:
        for i in range(len(spiral)):
            spiral[i].append(0)
        spiral = [[1 for _ in range(n)]] + spiral

    return spiral

print(np.array(my_spiral_ones(9)))

[[1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 0]
 [1 0 1 1 1 1 1 1 0]
 [1 0 1 0 0 0 0 1 0]
 [1 0 1 0 1 1 0 1 0]
 [1 0 1 0 0 1 0 1 0]
 [1 0 1 1 1 1 0 1 0]
 [1 0 0 0 0 0 0 1 0]
 [1 1 1 1 1 1 1 1 0]]
